root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app/fleetos-cloud ./cmd/fleetos-cloud/"
bin = "tmp/app"

full_bin = "chmod +x ./tmp/app/fleetos-cloud && ./tmp/app/fleetos-cloud"
log = "air_errors.log"

include_ext = ["go", "yml", "html"]
exclude_dir = ["tmp"]

delay = 1000

[log]
time = true

[misc]
clean_on_exit = true
