volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      .env
    environment:
      - PORT
      - DEV
      - DATABASE_URL
      - CACHE_URL
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - emqx

  redis:
    image: "redis:alpine"
    hostname: redis.fleetos
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:14-alpine
    hostname: postgres.fleetos
    ports:
      - "5432:5432"
    volumes:
      - ~apps/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres

  emqx:
    image: emqx/emqx-enterprise:5.10.0
    hostname: emqx.fleetos
    environment:
    - "EMQX_NODE_NAME=emqx@emqx.fleetos"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx.fleetos]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083


networks:
  emqx-bridge:
    driver: bridge
